@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package buildcraft.compat.module.jei.transferhandlers;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;