@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package buildcraft.compat.module.jei.energy.combustionengine;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;